version: '3'
volumes:
  postgres-gorch:

services:
  time_tracking:
    image: 'bezbasheniy/time_tracking:latest'
    build:
      context: .

    container_name: gorchanyuk_time_tracking
    working_dir: /usr/src/myapp
    ports:
      - "80:80"
    depends_on:
      database:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/t1
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  database:
    container_name: database
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t1
    volumes:
      - postgres-gorch:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 20s
      timeout: 10s
      retries: 5
